CREATE OR REPLACE PROCEDURE INSERT_CELEBRITY
(
 FIRST_NAME VARCHAR2, LAST_NAME VARCHAR2,
 STAGE_NAME VARCHAR2, GENDER VARCHAR2,
 NET_WORTH NUMBER, BIRTH_DATE DATE,
 INDUSTRY_ID NUMBER
)
AS
BEGIN
 INSERT INTO CELEBRITY VALUES(NULL, FIRST_NAME,LAST_NAME, STAGE_NAME, GENDER, NET_WORTH, BIRTH_DATE, INDUSTRY_ID);
 COMMIT;
END;
/

EXEC INSERT_CELEBRITY('NATALIE','DORMER',NULL,'F',100000, NULL, 1);

SELECT * FROM CELEBRITY;