--SEQUENCE USED TO AUTO INCREMENT
CREATE SEQUENCE CELEBRITY_SEQ
  START WITH 1
  INCREMENT BY 1;
  
--TRIGGER THAT WILL INCREMENT THE SEQUENCE
--AND ALTER THE PRIMARY KEY VALUE OF AN INSERT
CREATE OR REPLACE TRIGGER CELEBRITY_B_INSERT
BEFORE INSERT
ON CELEBRITY
FOR EACH ROW
BEGIN
  /* INCREASE THE SEQUENCE */
  --IF YOU DON'T WANT USERS TO INSERT ANY VALUE TO THE PK
  --COLUMN, REMOVE THE IF STATEMENT.
  IF :NEW.C_ID IS NULL THEN
    SELECT CELEBRITY_SEQ.NEXTVAL INTO :NEW.C_ID FROM DUAL;
  END IF;
END;
/
-- FORWARD SLASH
SELECT CELEBRITY_SEQ.NEXTVAL FROM DUAL;

DESCRIBE CELEBRITY;
INSERT INTO CELEBRITY 
VALUES(NULL,'Jim','Carrey',NULL,'M',NULL,NULL,1);

SELECT MAX(C_ID) FROM CELEBRITY;
