/* ON CHINOOK */
DESCRIBE ALBUM;
DESCRIBE ARTIST;

/* Give me the Albums with Artist */
SELECT AL.TITLE AS ALBUM_NAME, AR.NAME AS ARTIST_NAME
FROM ALBUM AL INNER JOIN ARTIST AR
ON AL.ARTISTID = AR.ARTISTID;

SELECT AL.TITLE AS ALBUM_NAME, AR.NAME AS ARTIST_NAME
FROM ALBUM AL, ARTIST AR
WHERE AL.ARTISTID = AR.ARTISTID;

--CROSS JOIN
--347
SELECT COUNT(*) FROM ALBUM;
--275
SELECT COUNT(*) FROM ARTIST;

--347 x 275 = 95425
SELECT COUNT(*)
FROM ALBUM AL, ARTIST AR;

--SELF JOIN
--Employees and their managers, AND THE BOSS that doesn't have a manager
SELECT E1.FIRSTNAME AS EMPLOYEE_NAME, E2.FIRSTNAME AS MANAGER_NAME
FROM EMPLOYEE E1 LEFT JOIN EMPLOYEE E2
ON E1.REPORTSTO = E2.EMPLOYEEID;

--EMPLOYEE'S WITH THEIR MANAGERS, end employee's who don't manage
SELECT NVL(E1.FIRSTNAME,'DOESNT_MANAGE') AS EMPLOYEE_NAME, E2.FIRSTNAME AS MANAGER_NAME
FROM EMPLOYEE E1 RIGHT JOIN EMPLOYEE E2
ON E1.REPORTSTO = E2.EMPLOYEEID;

SELECT NVL(E1.FIRSTNAME,'DOESNT_MANAGE') AS EMPLOYEE_NAME, E2.FIRSTNAME AS MANAGER_NAME
FROM EMPLOYEE E1 RIGHT JOIN EMPLOYEE E2
ON E1.REPORTSTO = E2.EMPLOYEEID
WHERE E1.REPORTSTO IS NULL;

/* ON CELEBRITY_DB */
SELECT * FROM CELEBRITY;

INSERT INTO CELEBRITY(C_ID,C_FIRST_NAME,C_LAST_NAME,C_GENDER)
VALUES(7,'Helen','Mirren','F');

--Give me the artist that work in a specific industry
SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, I.I_NAME
FROM CELEBRITY C INNER JOIN INDUSTRY I
ON C.I_ID = I.I_ID;

--Give me the artists that work in a specific industry
--and not.
--NVL SCALAR FUNCTION
SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM CELEBRITY C LEFT JOIN INDUSTRY I
ON C.I_ID = I.I_ID
WHERE C.I_ID IS NULL;

SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM CELEBRITY C, INDUSTRY I
WHERE C.I_ID = I.I_ID(+) AND C.I_ID IS NULL;

--Give me the industries which artist work in and
--industries that no one works at.
SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM CELEBRITY C RIGHT JOIN INDUSTRY I
ON C.I_ID = I.I_ID
WHERE C.I_ID IS NULL;

SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM CELEBRITY C, INDUSTRY I
WHERE C.I_ID(+) = I.I_ID AND C.I_ID IS NULL;

INSERT INTO INDUSTRY VALUES(3,'SPORTS');

--ARTISTS that don't work in any industry
-- And industry that no one likes
SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM INDUSTRY I FULL JOIN CELEBRITY C
ON C.I_ID = I.I_ID
WHERE C.I_ID IS NULL;

SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM CELEBRITY C, INDUSTRY I
WHERE C.I_ID(+) = I.I_ID AND C.I_ID IS NULL
UNION
SELECT C.C_FIRST_NAME || ', ' || C.C_LAST_NAME AS NAME, NVL(I.I_NAME, 'NO INDUSTRY')
FROM CELEBRITY C, INDUSTRY I
WHERE C.I_ID = I.I_ID(+) AND C.I_ID IS NULL;